service: auth-lambda

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  secretName:
    dev: dev/fl-admin-portal
    prod: prod/fl-admin-portal

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  timeout: 60
  memorySize: 1024
  ephemeralStorageSize: 10240
  architecture: arm64
  environment:
    AWS_SECRET_NAME: ${self:custom.secretName.${sls:stage}}
    NEO4J_ENCRYPTED: 'false'

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
