/**
 * Reusable Cypher query fragments for member authentication and role resolution
 */

export const MEMBER_FLAGS_QUERY = `{
  leadsBacenta:           exists((m)-[:LEADS]->(:Bacenta)),
  leadsBacentaOf:         head([(m)-[:LEADS]->(x:Bacenta)       | {id: x.id, name: x.name}]),
  leadsGovernorship:      exists((m)-[:LEADS]->(:Governorship)),
  leadsGovernorshipOf:    head([(m)-[:LEADS]->(x:Governorship)  | {id: x.id, name: x.name}]),
  leadsCouncil:           exists((m)-[:LEADS]->(:Council)),
  leadsCouncilOf:         head([(m)-[:LEADS]->(x:Council)       | {id: x.id, name: x.name}]),
  leadsStream:            exists((m)-[:LEADS]->(:Stream)),
  leadsStreamOf:          head([(m)-[:LEADS]->(x:Stream)        | {id: x.id, name: x.name}]),
  leadsCampus:            exists((m)-[:LEADS]->(:Campus)),
  leadsCampusOf:          head([(m)-[:LEADS]->(x:Campus)        | {id: x.id, name: x.name}]),
  leadsOversight:         exists((m)-[:LEADS]->(:Oversight)),
  leadsOversightOf:       head([(m)-[:LEADS]->(x:Oversight)     | {id: x.id, name: x.name}]),
  leadsDenomination:      exists((m)-[:LEADS]->(:Denomination)),
  leadsDenominationOf:    head([(m)-[:LEADS]->(x:Denomination)  | {id: x.id, name: x.name}]),
  isAdminForCampus:           exists((m)-[:IS_ADMIN_FOR]->(:Campus)),
  isAdminForCampusOf:         head([(m)-[:IS_ADMIN_FOR]->(x:Campus)        | {id: x.id, name: x.name}]),
  isAdminForGovernorship:     exists((m)-[:IS_ADMIN_FOR]->(:Governorship)),
  isAdminForGovernorshipOf:   head([(m)-[:IS_ADMIN_FOR]->(x:Governorship)  | {id: x.id, name: x.name}]),
  isAdminForCouncil:          exists((m)-[:IS_ADMIN_FOR]->(:Council)),
  isAdminForCouncilOf:        head([(m)-[:IS_ADMIN_FOR]->(x:Council)       | {id: x.id, name: x.name}]),
  isAdminForStream:           exists((m)-[:IS_ADMIN_FOR]->(:Stream)),
  isAdminForStreamOf:         head([(m)-[:IS_ADMIN_FOR]->(x:Stream)        | {id: x.id, name: x.name}]),
  isAdminForOversight:        exists((m)-[:IS_ADMIN_FOR]->(:Oversight)),
  isAdminForOversightOf:      head([(m)-[:IS_ADMIN_FOR]->(x:Oversight)     | {id: x.id, name: x.name}]),
  isAdminForDenomination:     exists((m)-[:IS_ADMIN_FOR]->(:Denomination)),
  isAdminForDenominationOf:   head([(m)-[:IS_ADMIN_FOR]->(x:Denomination)  | {id: x.id, name: x.name}]),
  isArrivalsAdminForStream:       exists((m)-[:DOES_ARRIVALS_FOR]->(:Stream)),
  isArrivalsAdminForStreamOf:     head([(m)-[:DOES_ARRIVALS_FOR]->(x:Stream)  | {id: x.id, name: x.name}]),
  isArrivalsAdminForCampus:       exists((m)-[:DOES_ARRIVALS_FOR]->(:Campus)),
  isArrivalsAdminForCampusOf:     head([(m)-[:DOES_ARRIVALS_FOR]->(x:Campus)  | {id: x.id, name: x.name}]),
  isArrivalsAdminForCouncil:      exists((m)-[:DOES_ARRIVALS_FOR]->(:Council)),
  isArrivalsAdminForCouncilOf:    head([(m)-[:DOES_ARRIVALS_FOR]->(x:Council) | {id: x.id, name: x.name}]),
  isArrivalsCounterForStream:     exists((m)-[:COUNTS_ARRIVALS_FOR]->(:Stream)),
  isArrivalsCounterForStreamOf:   head([(m)-[:COUNTS_ARRIVALS_FOR]->(x:Stream)     | {id: x.id, name: x.name}]),
  isArrivalsPayerCouncil:         exists((m)-[:IS_ARRIVALS_PAYER_FOR]->(:Council)),
  isArrivalsPayerCouncilOf:       head([(m)-[:IS_ARRIVALS_PAYER_FOR]->(x:Council)  | {id: x.id, name: x.name}]),
  isTellerForStream:              exists((m)-[:IS_TELLER_FOR]->(:Stream)),
  isTellerForStreamOf:            head([(m)-[:IS_TELLER_FOR]->(x:Stream)           | {id: x.id, name: x.name}]),
  isSheepSeekerForStream:         exists((m)-[:IS_SHEEP_SEEKER_FOR]->(:Stream)),
  isSheepSeekerForStreamOf:       head([(m)-[:IS_SHEEP_SEEKER_FOR]->(x:Stream)     | {id: x.id, name: x.name}]),
  isFisher:                       m.isFisher
} AS flags`
